services:
  - type: web
    name: extreme-frontier
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: VITE_DISCORD_CLIENT_ID
        sync: false
